export const $container_results = document.querySelector(".container_results")
export const $result = document.querySelectorAll(".result")
export const $btn_filter = document.querySelectorAll(".btn_filter")
export const $btn_all = document.getElementById("btn_all")
export const $btn_usdt = document.getElementById("btn_usdt")
export const $btn_busd = document.getElementById("btn_busd")
export const $btn_filterSave = document.getElementById("btn_filterSave")
export const $inp_search = document.getElementById("search_inp")
